include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    empty_catches: ignore

linter:
  rules:
    curly_braces_in_flow_control_structures: true
    # avoid_print: false
    # prefer_single_quotes: true
